### ISSUE TITLE
Interface for a sampling approach?

### ISSUE THREAD

**Issue by meshula** [sansumbrella/Choreograph#33]
The recommended interface to the timeline object is the dt step. If Choreograph were to be used to derive say audio envelopes, it might need to be called in batches because hundreds to thousands of samples might need to be generated per render quantum. At the moment, that would require jumping through to the lambda to get to the phrase, for each sample. It would be nice to have, for efficiency, a batch sampling mechanism, that would be along the lines of

timeline.jumpToTime(t);
timeline.sample(dt, 128);

That would need an iterating, version of phrases though.

Anyway, just a thought.

**Comment by sansumbrella** [comment]
I don't fully understand this suggestion, though I like the idea of Choreograph being applicable to audio.

Does the proposed `sample` method return the value of the 128th timeline item, or does it evaluate the first 128 timeline items?

A lot of Choreograph was written in a semi-vacuum, so I welcome ways to make different use cases simpler and/or possible.

**Comment by meshula** [comment]
FWIW, the proposal meant jump to t, then read 128 samples, at 

t + dt, t + 2dt, t + 3dt, t + 4dt, etc
