### ISSUE TITLE
Ability to animate via setter?

### ISSUE THREAD

**Issue by CoreyDotCom** [sansumbrella/Choreograph#35]
Is there currently a mechanism to invoke a setter or provide an arbitrary lambda to do the actual value application when a value changes?

This is useful/valuable for animating properties on objects that need to set a flag or invalidate something when values change (such as visual elements that need to be repainted on a given frame of animation or some such).

 Similarly is it feasible to specify a getter to pull the current "value" rather than a flat property?

**Comment by sansumbrella** [comment]
If you want to call a setter while animating, you can use a Motion's [updateFn](https://github.com/sansumbrella/Choreograph/blob/master/src/choreograph/Motion.hpp#L112) to do work immediately after the Output's value is changed.

**Comment by sansumbrella** [comment]
If you want to do value-based animation, you can skip the Timeline entirely and query your Sequence for its [value at a given time](https://github.com/sansumbrella/Choreograph/blob/master/src/choreograph/Sequence.hpp#L151-L152).

```
auto seq = Sequence<vec3>(vec3(0)).then<RampTo>(vec3(10), 1.0f);
seq->getValue(0.5); // => vec3(5);
```

**Comment by sansumbrella** [comment]
I edited my responses above to include example code. Let me know if those answer your question, or if there is something else you were thinking of.

**Comment by sansumbrella** [comment]
Let me know if the above responses answer your question. Closing.
