### ISSUE TITLE
Master branch, IOS sample does not build

### ISSUE THREAD

**Issue by eighteight** [sansumbrella/Choreograph#39]
![screen shot 2016-01-26 at 12 44 26 pm](https://cloud.githubusercontent.com/assets/542368/12589195/928ef590-c42a-11e5-9750-1319c7cac576.png)

**Comment by sansumbrella** [comment]
I just updated the iOS sample to build against a recent version of Cinder (updated boost path, etc). Let me know if that fixes it for you.

I never saw the object parameter initialization error in your screenshot. Are you building for the device or the simulator?

**Comment by eighteight** [comment]
It's working, thank you. I am running this sample on device.
