### ISSUE TITLE
Control fps

### ISSUE THREAD

**Issue by nvcken** [sansumbrella/Choreograph#46]
How the way we can control fps?
Example to ensure the animation looks smooth at ~60fps

**Comment by sansumbrella** [comment]
All `TimelineItem`s in Choreograph have a `step(dt)` method that receives a delta time. You can adjust how much animation time elapses per frame of your application by passing a larger or smaller delta time into your timeline's step method.

If you want to ensure animation requires a fixed amount of clock time, delta time should be equivalent to the actual frame delta. Smoothing framerate inconsistencies in an application can be more complicated, and irregular framerates will never look perfectly smooth no matter how the animation is manipulated, but in general controlling a timeline with clock time will look good.

**Comment by nvcken** [comment]
Thanks.
Beside the way we can determine the animation is smooth or not by human eyes, is any other way which can automation detect & check that ? ^_^

**Comment by sansumbrella** [comment]
Not that I'm aware of.

Any kind of automatic smoothing would change the character of the motion, and Choreograph exists to help you express the kind of motion you want. If you want smooth motion, you will need to make sure your motions don't have any discontinuous pieces and ensure that your application runs with a consistent framerate.
